### ISSUE TITLE
Modify list to reduce words changed

### ISSUE THREAD

**Issue by jasonpstokes** [jdanders/calibre-plugin-language-cleaner#4]
Hi, thanks for this plugin - impressive! How do I modify the script to reduce the word changes please (and some substituted words), as when I try it breaks and doesn't do anything. Any tips please?

e.g. In this extreme example, to just keep the f' bomb section:
[Language_cleaner_custom.zip](https://github.com/jdanders/calibre-plugin-language-cleaner/files/11911097/Language_cleaner_custom.zip)

PS an example where it doesn't work well (for me):
`“Shut up,” Mensah snapped. “You shut the mess up. We’re not leaving you.”`

**Comment by jdanders** [comment]
Thanks for raising the issue, I just made a commit that should fix that particular case.

I'll need more information to help you modify it and use it without breaking. The instructions in the readme should be good enough. One tip would be to try running `python3` interactively and try importing `from cleaner import *` to check for typos. There's a commented section at the end of cleaner.py that you can use to test things interacively.

**Comment by jasonpstokes** [comment]
Sorry, I never replied to say thanks for taking a look and updating the script.

I ended up manually editing that book, but will try this next time. Appreciate your time to create and share this script. 

(It's a shame author's won't expand their vocabularies. I get swearing is now a big part of western culture, but there are many ways to express something without swearing, that would also make a book available to a wider audience.)
